apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: "{{ include "csa.name.namespace" . }}"
  name: "{{ include "csa.name.release" . }}"
  {{- include "csa.label.serviceaccount" . | indent 2 }}
  {{- include "csa.annotation.serviceaccount" . | indent 2 }}
