name: Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  unit:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Test
        run: make test-run-unit

  integration:
    name: Run integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Kind
        uses: helm/kind-action@v1.8.0
        with:
          install_only: true
          version: v0.20.0
          kubectl_version: v1.27.2

      - name: Test
        env:
          MAX_PARALLELISM: 1 # Constrained to 2 CPUs on ubuntu-latest
        run: make test-run-int-verbose KUBE_VERSION=1.29 # TODO(wt) test against potentially many versions

  helm:
    name: Run Helm tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test
        run: make test-run-helm
